/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'ix:about',
      order: 10
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 2,
      roles: ['admin']
    },
    children: [
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict',
          icon: 'streamline:dictionary-language-book',
          order: 4,
          roles: ['admin']
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['admin'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['superadmin']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['admin']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['admin'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor',
      icon: 'eos-icons:monitoring',
      roles: ['admin'],
      order: 3
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache',
          icon: 'octicon:cache-24',
          roles: ['admin'],
          order: 2
        }
      },
      {
        name: 'monitor_log',
        path: '/monitor/log',
        meta: {
          title: 'monitor_log',
          i18nKey: 'route.monitor_log',
          icon: 'material-symbols:list-alt-outline-rounded',
          roles: ['admin'],
          order: 3
        },
        children: [
          {
            name: 'monitor_log_login',
            path: '/monitor/log/login',
            component: 'view.monitor_log_login',
            meta: {
              title: 'monitor_log_login',
              i18nKey: 'route.monitor_log_login',
              icon: 'ri:contacts-book-3-line',
              roles: ['admin'],
              order: 4
            }
          },
          {
            name: 'monitor_log_operate',
            path: '/monitor/log/operate',
            component: 'view.monitor_log_operate',
            meta: {
              title: 'monitor_log_operate',
              i18nKey: 'route.monitor_log_operate',
              icon: 'material-symbols-light:developer-board-outline',
              roles: ['admin'],
              order: 3
            }
          }
        ]
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online',
          icon: 'carbon:user-online',
          roles: ['admin'],
          order: 1
        }
      }
    ]
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'material-symbols:settings-account-box-outline',
      order: 9
    },
    children: [
      {
        name: 'settings_account',
        path: '/settings/account',
        component: 'view.settings_account',
        meta: {
          title: 'settings_account',
          i18nKey: 'route.settings_account',
          icon: 'material-symbols:lock-person-outline',
          order: 2
        }
      },
      {
        name: 'settings_profile',
        path: '/settings/profile',
        component: 'view.settings_profile',
        meta: {
          title: 'settings_profile',
          i18nKey: 'route.settings_profile',
          icon: 'material-symbols:person-play-outline',
          order: 1
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true,
      icon: 'carbon:user-avatar'
    }
  }
];
